//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirGrepUI.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirGrepUI.Resources.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &amp;Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search process does not finish yet 
        ///Do you want to terminate the application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error ocurred に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search process does not finish yet 
        ///Do you want to terminate the application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file cannot be opened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotOpen {
            get {
                return ResourceManager.GetString("FileNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder path is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderPathError {
            get {
                return ResourceManager.GetString("FolderPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given file extension does not exist in selected folder. Please type again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IncorrectTextEditor {
            get {
                return ResourceManager.GetString("IncorrectTextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to stop search process? [Yes] [No] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The given file extension does not exist in selected folder. Please type again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetNotExist {
            get {
                return ResourceManager.GetString("TargetNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SearchPlace or SearchText is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBoxEmpty {
            get {
                return ResourceManager.GetString("TextBoxEmpty", resourceCulture);
            }
        }
    }
}
